### ISSUE TITLE
Code of Conduct and reporting process

### ISSUE THREAD

**Issue by dthaler** [l3af-project/governance#3]
We need to document the Code of Conduct (ideally based on Contributor Covenant), and the process for reporting any issues.

According to https://www.contributor-covenant.org/ the latest is v2.1 and the "How to Adopt Contributor Covenant" section there explains what would need to be done.

**Comment by vmbrasseur** [comment]
Huh. I guess I misremembered that v4.0. Apologies on that.

Regardless, +1 to using Contributor Covenant v2.1, unless there's a more standard LFN option.

_(if we use the Contributor Convenant, btw, we'll need an email address (or other contact method, but email address is likely easiest) that people can use for reporting concerns. This contact method must be added in the the appropriate location in the CoC template, which will then be added to this repository & referenced across all L3AF repos/projects.)_

How other LFN projects do this:

* LFN itself: The [LFN wiki](https://wiki.lfnetworking.org) links to the [LF events CoC](https://events.linuxfoundation.org/about/code-of-conduct/), which seems like a bad idea. It doesn't make sense for LF's VP of events (Angela) to be receiving CoC concerns for LFN?
* Anuket: Uses the [LF Projects Code of Conduct](https://lfprojects.org/policies/code-of-conduct/). This seems a reasonable route to take, IMO.
* ONAP: Does the same as Anuket. That's another point in favour of using the LF Projects CoC & reporting method.
* EMCO: Uses [Contrib Cov v1.4](https://gitlab.com/project-emco/core/emco-base/-/blob/main/CODE_OF_CONDUCT.md), but phones it in with "may be reported by contacting the EMCO maintainers." Making reporters work to locate contact info discourages reports. (also, they added an Apache-2.0 SPDX  tag & Copyright Intel to the top of the file, despite neither of those bits of information being correct; looks like they scripted the SPDX tag adding w/o regard to non-Apache-licensed files or files that have different copyright)
* fd.io: Proving to be a pain in the butt to locate their CoC. Moving on.
* ODIM: Uses LF Projects CoC & reporting method
* Open Daylight: CoC must be there somewhere but it's not obvious. Moving on.
* Tungsten Fabric: I know this _used_ to have a CoC because I added it, but it's not showing up with a quick skim. Moving on.
* XGVela: Uses LF Projects CoC & reporting method

It looks like most of the LFN project point to [LF Projects CoC](https://lfprojects.org/policies/code-of-conduct/). I suggest we do the same since we're looking to apply to be an LFN project.

**Comment by vmbrasseur** [comment]
According to section 4b of the charter (to be merged in #15):

> The TSC may adopt a code of conduct (“CoC”) for the Project, which is subject to approval by the Series Manager. In the event that a Project-specific CoC has not been approved, the LF Projects [Code of Conduct](https://lfprojects.org/policies) will apply for all Collaborators in the Project.

I'm happy to do that for now, but we should make it explicit via files in the repos.

**Comment by vmbrasseur** [comment]
@dthaler Have a quick look at PR #18? (for some reason I can't tag you on it for a review).

**Comment by vmbrasseur** [comment]
The org-level CoC work will happen in #17.

Closing this issue.
